version: '{branch}.{build}'
branches:
  only:
  - master
  - appveyor
  - w32
  - windows

image:
#- Visual Studio 2015
- Visual Studio 2017

platform:
- x86
- x64

install:
- cmd: cinst wget
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
- cmd: set ARTIFACT_DIR=%APPVEYOR_BUILD_FOLDER%\artifacts

build_script:
# check
- cmd: >-
    set CHECK_SRC_DIR=\projects\check

    set CHECK_BUILD_DIR=%CHECK_SRC_DIR%\build

    set CHECK_DIR=%ARTIFACT_DIR%

    set CHECK_INCLUDE_DIR=%CHECK_DIR%\include

    set CHECK_LIBRARY=%CHECK_DIR%\lib

    git clone -b master https://github.com/libcheck/check.git %CHECK_SRC_DIR%

    mkdir %CHECK_BUILD_DIR%

    cd %CHECK_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CHECK_DIR% ..

    nmake

    nmake install
# json-c
- cmd: >-
    set LIBJSONC_SRC_DIR=\projects\json-c

    set LIBJSONC_BUILD_DIR=%LIBJSONC_SRC_DIR%\build

    set LIBJSONC_DIR=%ARTIFACT_DIR%

    set LIBJSONC_INCLUDE_DIR=%LIBJSONC_DIR%\include

    set LIBJSONC_LIBRARY=%LIBJSONC_DIR%\lib

    git clone -b windows https://github.com/jbboehr/json-c.git %LIBJSONC_SRC_DIR%

    mkdir %LIBJSONC_BUILD_DIR%

    cd %LIBJSONC_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBJSONC_DIR% ..

    nmake

    nmake install
# pcre
- cmd: >-
    set PCRE_SRC_DIR=\projects\pcre

    set PCRE_BUILD_DIR=%PCRE_SRC_DIR%\build

    set PCRE_DIR=%ARTIFACT_DIR%

    set PCRE_INCLUDE_DIR=%PCRE_DIR%\include

    set PCRE_LIBRARY=%PCRE_DIR%\lib

    git clone https://github.com/jbboehr/pcre.git %PCRE_SRC_DIR%

    mkdir %PCRE_BUILD_DIR%

    cd %PCRE_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PCRE_DIR% ..

    nmake

    nmake install
# talloc
- cmd: >-
    set TALLOC_SRC_DIR=\projects\talloc-win

    set TALLOC_BUILD_DIR=%TALLOC_SRC_DIR%\build

    set TALLOC_DIR=%ARTIFACT_DIR%

    set TALLOC_INCLUDE_DIR=%TALLOC_DIR%\include

    set TALLOC_LIBRARY=%TALLOC_DIR%\lib

    git clone https://github.com/jbboehr/talloc-win.git %TALLOC_SRC_DIR%

    mkdir %TALLOC_BUILD_DIR%

    cd %TALLOC_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%TALLOC_DIR% ..

    nmake

    nmake install
# yaml
- cmd: >-
    set LIBYAML_SRC_DIR=\projects\yaml

    set LIBYAML_BUILD_DIR=%LIBYAML_SRC_DIR%\build

    set LIBYAML_DIR=%ARTIFACT_DIR%

    set LIBYAML_INCLUDE_DIR=%LIBYAML_DIR%\include

    set LIBYAML_LIBRARY=%LIBYAML_DIR%\lib

    git clone https://github.com/yaml/libyaml %LIBYAML_SRC_DIR%

    mkdir %LIBYAML_BUILD_DIR%

    cd %LIBYAML_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBYAML_DIR% ..

    nmake

    copy /Y *.lib %LIBYAML_INCLUDE_DIR%

    copy /Y ..\include\yaml.h %LIBYAML_LIBRARY%
# handlebars
- cmd: >-
    set HANDLEBARS_SRC_DIR=%APPVEYOR_BUILD_FOLDER%

    set HANDLEBARS_BUILD_DIR=%HANDLEBARS_SRC_DIR%\cmake-build

    set HANDLEBARS_DIR=%APPVEYOR_BUILD_FOLDER%\artifacts

    mkdir %HANDLEBARS_BUILD_DIR%

    cd %HANDLEBARS_BUILD_DIR%

    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%HANDLEBARS_DIR% -DCHECK_INCLUDE_DIRS=%CHECK_INCLUDE_DIR% -DCHECK_LIBRARIES=%CHECK_LIBRARY% -DLIBJSONC_INCLUDE_DIR=%LIBJSONC_INCLUDE_DIR% -DLIBJSONC_LIBRARY=%LIBJSONC_LIBRARY% -DLIBYAML_INCLUDE_DIRS=%LIBYAML_INCLUDE_DIR% -DLIBYAML_LIBRARIES=%LIBYAML_LIBRARY% -DPCRE_INCLUDE_DIRS=%PCRE_INCLUDE_DIR% -DPCRE_LIBRARIES=%PCRE_LIBRARY% -DTALLOC_INCLUDE_DIRS=%TALLOC_INCLUDE_DIR% -DTALLOC_LIBRARIES=%TALLOC_LIBRARY% ..

    nmake

    nmake install

test_script:
- cmd: nmake test

artifacts:
  - path: artifacts
    name: master
    type: zip
