version: '{branch}.{build}'
branches:
  only:
  - master
  - appveyor
  - w32
  - windows

skip_commits:
  files:
    - "*.md"
    - ".travis*"

cache:
  - c:\build-cache

platform:
#- x86
- x64

environment:
  REPORT_EXIT_STATUS: 1
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.9
  BUILD_CACHE_DIR: C:\build-cache
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VC_VER: vc14
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VC_VER: vc15
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

install:
- cmd: cinst wget
- if defined VS call "%VS%" %PLATFORM%
- cmd: set ARTIFACT_DIR=%APPVEYOR_BUILD_FOLDER%\artifacts
- cmd: mkdir %ARTIFACT_DIR%\bin
- cmd: mkdir %ARTIFACT_DIR%\include
- cmd: mkdir %ARTIFACT_DIR%\lib
- cmd: git submodule update --init
- .appveyor.bat install

build_script:
- .appveyor.bat build_script
- cmd: cd %APPVEYOR_BUILD_FOLDER%\cmake-build

test_script:
- cmd: nmake test

artifacts:
  - path: artifacts
    name: master
    type: zip
