/* Generated by re2c 0.13.5 on Wed Feb 25 15:56:04 2015 */

#include "handlebars_scanners.h"

#define YYCTYPE char

short handlebars_scanner_next_whitespace(const char * s, short def)
{
    const YYCTYPE * YYCURSOR = s;
    
    for (;;) {
        
{
    YYCTYPE yych;

    yych = *YYCURSOR;
    if (yych <= '\v') {
        if (yych <= 0x08) {
            if (yych >= 0x01) goto yy8;
        } else {
            if (yych == '\n') goto yy6;
            goto yy4;
        }
    } else {
        if (yych <= '\r') {
            if (yych <= '\f') goto yy8;
            goto yy4;
        } else {
            if (yych == ' ') goto yy4;
            goto yy8;
        }
    }
    ++YYCURSOR;
    { break; }
yy4:
    ++YYCURSOR;
    { continue; }
yy6:
    ++YYCURSOR;
    { return 1; }
yy8:
    ++YYCURSOR;
    { return 0; }
}

    }
    
    return def;
}

short handlebars_scanner_prev_whitespace(const char * s, short def)
{
    const YYCTYPE * YYCURSOR = s;
    short match = def;
    
    for (;;) {
        
{
    YYCTYPE yych;
    yych = *YYCURSOR;
    if (yych <= '\v') {
        if (yych <= 0x08) {
            if (yych >= 0x01) goto yy18;
        } else {
            if (yych == '\n') goto yy16;
            goto yy14;
        }
    } else {
        if (yych <= '\r') {
            if (yych <= '\f') goto yy18;
            goto yy14;
        } else {
            if (yych == ' ') goto yy14;
            goto yy18;
        }
    }
    ++YYCURSOR;
    { break; }
yy14:
    ++YYCURSOR;
    { continue; }
yy16:
    ++YYCURSOR;
    { match = 1; continue; }
yy18:
    ++YYCURSOR;
    { match = 0; continue; }
}

    }
    
    return match;
}
