if (LIBYAML_LIBRARIES AND LIBYAML_INCLUDE_DIRS)
    set (LIBYAML_FIND_QUIETLY TRUE)
endif (LIBYAML_LIBRARIES AND LIBYAML_INCLUDE_DIRS)

find_path (LIBYAML_INCLUDE_DIRS NAMES yaml.h)
IF(MSVC)
    add_definitions(-DYAML_DECLARE_STATIC)
    find_library (LIBYAML_LIBRARIES NAMES yaml_static)
ELSE()
    find_library (LIBYAML_LIBRARIES NAMES yaml)
ENDIF()

if (LIBYAML_LIBRARIES)
    add_definitions(-DHAVE_LIBYAML)
endif()

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBYAML DEFAULT_MSG
    LIBYAML_LIBRARIES
    LIBYAML_INCLUDE_DIRS)

mark_as_advanced(LIBYAML_INCLUDE_DIRS LIBYAML_LIBRARIES)
