# Find the 8-bit PCRE2 library.
#
# PCRE2_INCLUDE_DIRS - where to find pcre2.h
# PCRE2_LIBRARIES    - libraries to link for PCRE2
# PCRE2_FOUND        - true if PCRE2 was found

FIND_PATH(PCRE2_INCLUDE_DIR NAMES pcre2.h)
FIND_LIBRARY(PCRE2_LIBRARY NAMES pcre2-8 pcre2-8-static)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE2 DEFAULT_MSG PCRE2_LIBRARY PCRE2_INCLUDE_DIR)

IF(PCRE2_FOUND)
    SET(PCRE2_LIBRARIES ${PCRE2_LIBRARY})
    SET(PCRE2_INCLUDE_DIRS ${PCRE2_INCLUDE_DIR})
ELSE()
    SET(PCRE2_LIBRARIES)
    SET(PCRE2_INCLUDE_DIRS)
ENDIF()

MARK_AS_ADVANCED(PCRE2_INCLUDE_DIR PCRE2_LIBRARY PCRE2_INCLUDE_DIRS PCRE2_LIBRARIES)
